// ------------ Session ---------
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR'

export const SIGN_OUT_CLEAR = 'SIGN_OUT_CLEAR'

// ----------- Auth ------------
export const ADD_PLATAFORMA = 'ADD_PLATAFORMA'

// ----------- User ------------
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR'

// ----------- GRUPOS ECONOMICOS ---------------
export const GET_GRUPOS_ECONOMICOS_REQUEST = 'GET_GRUPOS_ECONOMICOS_REQUEST'
export const GET_GRUPOS_ECONOMICOS_SUCCESS = 'GET_GRUPOS_ECONOMICOS_SUCCESS'
export const GET_GRUPOS_ECONOMICOS_ERROR = 'GET_GRUPOS_ECONOMICOS_ERROR'

export const GET_EMPRESA_GRUPOS_ECONOMICOS_REQUEST = 'GET_EMPRESA_GRUPOS_ECONOMICOS_REQUEST'
export const GET_EMPRESA_GRUPOS_ECONOMICOS_SUCCESS = 'GET_EMPRESA_GRUPOS_ECONOMICOS_SUCCESS'
export const GET_EMPRESA_GRUPOS_ECONOMICOS_ERROR = 'GET_EMPRESA_GRUPOS_ECONOMICOS_ERROR'

export const CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_REQUEST = 'CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_REQUEST'
export const CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_SUCCESS = 'CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_SUCCESS'
export const CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_ERROR = 'CLEAR_EMPRESAS_GRUPOS_ECONOMICOS_ERROR'

// ----------- MACROBANCAS -----------
export const GET_MACROBANCAS_REQUEST = 'GET_MACROBANCAS_REQUEST'
export const GET_MACROBANCAS_SUCCESS = 'GET_MACROBANCAS_SUCCESS'
export const GET_MACROBANCAS_ERROR = 'GET_MACROBANCAS_ERROR'

// ----------- EMPRESAS ---------------
export const GET_CARTERA_REQUEST = 'GET_CARTERA_REQUEST'
export const GET_CARTERA_SUCCESS = 'GET_CARTERA_SUCCESS'
export const GET_CARTERA_ERROR = 'GET_CARTERA_ERROR'

export const GET_EMPRESA_REQUEST = 'GET_EMPRESA_REQUEST'
export const GET_EMPRESA_SUCCESS = 'GET_EMPRESA_SUCCESS'
export const GET_EMPRESA_ERROR = 'GET_EMPRESA_ERROR'

export const VALIDATE_EMPRESA_REQUEST = 'VALIDATE_EMPRESA_REQUEST'
export const VALIDATE_EMPRESA_SUCCESS = 'VALIDATE_EMPRESA_SUCCESS'
export const VALIDATE_EMPRESA_ERROR = 'VALIDATE_EMPRESA_ERROR'

export const GET_PROSPECTO_REQUEST = 'GET_PROSPECTO_REQUEST'
export const GET_PROSPECTO_SUCCESS = 'GET_PROSPECTO_SUCCESS'
export const GET_PROSPECTO_ERROR = 'GET_PROSPECTO_ERROR'

export const CREATE_PROSPECTO_REQUEST = 'CREATE_PROSPECTO_REQUEST'
export const CREATE_PROSPECTO_SUCCESS = 'CREATE_PROSPECTO_SUCCESS'
export const CREATE_PROSPECTO_ERROR = 'CREATE_PROSPECTO_ERROR'

export const CLEAR_EMPRESA_REQUEST = 'CLEAR_EMPRESA_REQUEST'
export const CLEAR_EMPRESA_SUCCESS = 'CLEAR_EMPRESA_SUCCESS'
export const CLEAR_EMPRESA_ERROR = 'CLEAR_EMPRESA_ERROR'

// ----------- Oportunidades -----------
export const GET_OPORTUNIDADES_REQUEST = 'GET_OPORTUNIDADES_REQUEST'
export const GET_OPORTUNIDADES_SUCCESS = 'GET_OPORTUNIDADES_SUCCESS'
export const GET_OPORTUNIDADES_ERROR = 'GET_OPORTUNIDADES_ERROR'

export const GET_OPORTUNIDAD_REQUEST = 'GET_OPORTUNIDAD_REQUEST'
export const GET_OPORTUNIDAD_SUCCESS = 'GET_OPORTUNIDAD_SUCCESS'
export const GET_OPORTUNIDAD_ERROR = 'GET_OPORTUNIDAD_ERROR'

export const CREATE_OPORTUNIDAD_REQUEST = 'CREATE_OPORTUNIDAD_REQUEST'
export const CREATE_OPORTUNIDAD_SUCCESS = 'CREATE_OPORTUNIDAD_SUCCESS'
export const CREATE_OPORTUNIDAD_ERROR = 'CREATE_OPORTUNIDAD_ERROR'

export const UPDATE_OPORTUNIDAD_REQUEST = 'UPDATE_OPORTUNIDAD_REQUEST'
export const UPDATE_OPORTUNIDAD_SUCCESS = 'UPDATE_OPORTUNIDAD_SUCCESS'
export const UPDATE_OPORTUNIDAD_ERROR = 'UPDATE_OPORTUNIDAD_ERROR'

export const GET_LISTA_OPORTUNIDADES_BY_IDS_REQUEST = 'GET_LISTA_OPORTUNIDADES_BY_IDS_REQUEST'
export const GET_LISTA_OPORTUNIDADES_BY_IDS_SUCCESS = 'GET_LISTA_OPORTUNIDADES_BY_IDS_SUCCESS'
export const GET_LISTA_OPORTUNIDADES_BY_IDS_ERROR = 'GET_LISTA_OPORTUNIDADES_BY_IDS_ERROR'

export const UPDATE_DETALLE_OPORTUNIDAD = 'UPDATE_DETALLE_OPORTUNIDAD'

export const CLEAR_OPORTUNIDAD_SUCCESS = 'CLEAR_OPORTUNIDAD_SUCCESS'

// ------------- Visitas ----------------
export const GET_VISITAS_REQUEST = 'GET_VISITAS_REQUEST'
export const GET_VISITAS_SUCCESS = 'GET_VISITAS_SUCCESS'
export const GET_VISITAS_ERROR = 'GET_VISITAS_ERROR'

export const GET_VISITA_REQUEST = 'GET_VISITA_REQUEST'
export const GET_VISITA_SUCCESS = 'GET_VISITA_SUCCESS'
export const GET_VISITA_ERROR = 'GET_VISITA_ERROR'

export const GET_VISITAS_PRIORIZADA_REQUEST = 'GET_VISITAS_PRIORIZADA_REQUEST'
export const GET_VISITAS_PRIORIZADA_SUCCESS = 'GET_VISITAS_PRIORIZADA_SUCCESS'
export const GET_VISITAS_PRIORIZADA_ERROR   = 'GET_VISITAS_PRIORIZADA_ERROR'

export const GET_CANTIDAD_VISITAS_PRIORIZADA_REQUEST = 'GET_CANTIDAD_VISITAS_PRIORIZADA_REQUEST'
export const GET_CANTIDAD_VISITAS_PRIORIZADA_SUCCESS = 'GET_CANTIDAD_VISITAS_PRIORIZADA_SUCCESS'
export const GET_CANTIDAD_VISITAS_PRIORIZADA_ERROR   = 'GET_CANTIDAD_VISITAS_PRIORIZADA_ERROR'

export const GET_OPORTUNIDADES_VENCIDAD_REQUEST = 'GET_OPORTUNIDADES_VENCIDAD_REQUEST'
export const GET_OPORTUNIDADES_VENCIDAD_SUCCESS = 'GET_OPORTUNIDADES_VENCIDAD_SUCCESS'
export const GET_OPORTUNIDADES_VENCIDAD_ERROR   = 'GET_OPORTUNIDADES_VENCIDAD_ERROR '

export const SET_VISITAS_FILTER_PARAMS = 'SET_VISITAS_FILTER_PARAMS'

export const CREATE_VISITA_REQUEST = 'CREATE_VISITA_REQUEST'
export const CREATE_VISITA_SUCCESS = 'CREATE_VISITA_SUCCESS'
export const CREATE_VISITA_ERROR = 'CREATE_VISITA_ERROR'

export const UPDATE_VISITA_REQUEST = 'UPDATE_VISITA_REQUEST'
export const UPDATE_VISITA_SUCCESS = 'UPDATE_VISITA_SUCCESS'
export const UPDATE_VISITA_ERROR = 'UPDATE_VISITA_ERROR'

export const CLEAR_VISITA_SUCCESS = 'CLEAR_VISITA_SUCCESS'

//GET_TIPO_VISITA
export const GET_TIPO_VISITA_REQUEST = 'GET_TIPO_VISITA_REQUEST'
export const GET_TIPO_VISITA_SUCCESS = 'GET_TIPO_VISITA_SUCCESS'
export const GET_TIPO_VISITA_ERROR   = 'GET_TIPO_VISITA_ERROR '

// ------------- Riesgos ----------------
export const GET_LISTA_RIESGOS_BY_IDS_REQUEST = 'GET_LISTA_RIESGOS_BY_IDS_REQUEST'
export const GET_LISTA_RIESGOS_BY_IDS_SUCCESS = 'GET_LISTA_RIESGOS_BY_IDS_SUCCESS'
export const GET_LISTA_RIESGOS_BY_IDS_ERROR = 'GET_LISTA_RIESGOS_BY_IDS_ERROR'

export const GET_RIESGO_REQUEST = 'GET_RIESGO_REQUEST'
export const GET_RIESGO_SUCCESS = 'GET_RIESGO_SUCCESS'
export const GET_RIESGO_ERROR = 'GET_RIESGO_ERROR'

export const GET_VIGENCIA_RIESGOS_REQUEST = 'GET_VIGENCIA_RIESGOS_REQUEST'
export const GET_VIGENCIA_RIESGOS_SUCCESS = 'GET_VIGENCIA_RIESGOS_SUCCESS'
export const GET_VIGENCIA_RIESGOS_ERROR = 'GET_VIGENCIA_RIESGOS_ERROR'

export const SET_RIESGOS_FILTER_PARAMS = 'SET_RIESGOS_FILTER_PARAMS'

export const CREATE_RIESGO_REQUEST = 'CREATE_RIESGO_REQUEST'
export const CREATE_RIESGO_SUCCESS = 'CREATE_RIESGO_SUCCESS'
export const CREATE_RIESGO_ERROR = 'CREATE_RIESGO_ERROR'

export const UPDATE_RIESGO_REQUEST = 'UPDATE_RIESGO_REQUEST'
export const UPDATE_RIESGO_SUCCESS = 'UPDATE_RIESGO_SUCCESS'
export const UPDATE_RIESGO_ERROR = 'UPDATE_RIESGO_ERROR'

export const CLEAR_RIESGO_SUCCESS = 'CLEAR_RIESGO_SUCCESS'

// ----------- Colaboradores -----------
export const GET_COLABORADORES_REQUEST = 'GET_COLABORADORES_REQUEST'
export const GET_COLABORADORES_SUCCESS = 'GET_COLABORADORES_SUCCESS'
export const GET_COLABORADORES_ERROR = 'GET_COLABORADORES_ERROR'

export const GET_COLABORADORES_BUSQUEDA_REQUEST = 'GET_COLABORADORES_BUSQUEDA_REQUEST'
export const GET_COLABORADORES_BUSQUEDA_SUCCESS = 'GET_COLABORADORES_BUSQUEDA_SUCCESS'
export const GET_COLABORADORES_BUSQUEDA_ERROR = 'GET_COLABORADORES_BUSQUEDA_ERROR'

// ----------- Estados -----------
export const GET_ESTADOS_OPORTUNIDAD_REQUEST = 'GET_ESTADOS_OPORTUNIDAD_REQUEST'
export const GET_ESTADOS_OPORTUNIDAD_SUCCESS = 'GET_ESTADOS_OPORTUNIDAD_SUCCESS'
export const GET_ESTADOS_OPORTUNIDAD_ERROR = 'GET_ESTADOS_OPORTUNIDAD_ERROR'

// ----------- Formulario Oportunidad -----------
export const GET_FORMULARIO_INICIAL_OPORTUNIDAD_REQUEST = 'GET_FORMULARIO_INICIAL_OPORTUNIDAD_REQUEST'
export const GET_FORMULARIO_INICIAL_OPORTUNIDAD_SUCCESS = 'GET_FORMULARIO_INICIAL_OPORTUNIDAD_SUCCESS'
export const GET_FORMULARIO_INICIAL_OPORTUNIDAD_ERROR = 'GET_FORMULARIO_INICIAL_OPORTUNIDAD_ERROR'

export const GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_REQUEST = 'GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_REQUEST'
export const GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_SUCCESS = 'GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_SUCCESS'
export const GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_ERROR = 'GET_PREGUNTAS_FORMULARIO_OPORTUNIDAD_ERROR'

export const CLEAR_FORMULARIO_OPORTUNIDAD_SUCCESS = 'CLEAR_FORMULARIO_OPORTUNIDAD_SUCCESS'

export const REPLACE_FORMULARIO_OPORTUNIDAD_ATTRIBUTES = 'REPLACE_FORMULARIO_OPORTUNIDAD_ATTRIBUTES'

// ----------- Filtros Oportunidad -----------
export const GET_FILTRO_INICIAL_OPORTUNIDAD_REQUEST = 'GET_FILTRO_INICIAL_OPORTUNIDAD_REQUEST'
export const GET_FILTRO_INICIAL_OPORTUNIDAD_SUCCESS = 'GET_FILTRO_INICIAL_OPORTUNIDAD_SUCCESS'
export const GET_FILTRO_INICIAL_OPORTUNIDAD_ERROR = 'GET_FILTRO_INICIAL_OPORTUNIDAD_ERROR'

export const GET_PREGUNTAS_FILTRO_OPORTUNIDAD_REQUEST = 'GET_PREGUNTAS_FILTRO_OPORTUNIDAD_REQUEST'
export const GET_PREGUNTAS_FILTRO_OPORTUNIDAD_SUCCESS = 'GET_PREGUNTAS_FILTRO_OPORTUNIDAD_SUCCESS'
export const GET_PREGUNTAS_FILTRO_OPORTUNIDAD_ERROR = 'GET_PREGUNTAS_FILTRO_OPORTUNIDAD_ERROR'

export const CLEAR_FILTRO_OPORTUNIDAD_SUCCESS = 'CLEAR_FILTRO_OPORTUNIDAD_SUCCESS'
export const RESTORE_BACKUP_FILTRO_OPORTUNIDAD_SUCCESS = 'RESTORE_BACKUP_FILTRO_OPORTUNIDAD_SUCCESS'

export const REPLACE_FILTRO_OPORTUNIDAD_ATTRIBUTES = 'REPLACE_FILTRO_OPORTUNIDAD_ATTRIBUTES'

export const SET_OPORTUNIDAD_FILTER_PARAMS = 'SET_OPORTUNIDAD_FILTER_PARAMS'

// ----------- Formulario Visita -----------
export const GET_FORMULARIO_INICIAL_VISITA_REQUEST = 'GET_FORMULARIO_INICIAL_VISITA_REQUEST'
export const GET_FORMULARIO_INICIAL_VISITA_SUCCESS = 'GET_FORMULARIO_INICIAL_VISITA_SUCCESS'
export const GET_FORMULARIO_INICIAL_VISITA_ERROR = 'GET_FORMULARIO_INICIAL_VISITA_ERROR'

export const GET_PREGUNTAS_FORMULARIO_VISITA_REQUEST = 'GET_PREGUNTAS_FORMULARIO_VISITA_REQUEST'
export const GET_PREGUNTAS_FORMULARIO_VISITA_SUCCESS = 'GET_PREGUNTAS_FORMULARIO_VISITA_SUCCESS'
export const GET_PREGUNTAS_FORMULARIO_VISITA_ERROR = 'GET_PREGUNTAS_FORMULARIO_VISITA_ERROR'

export const CLEAR_FORMULARIO_VISITA_REQUEST = 'CLEAR_FORMULARIO_VISITA_REQUEST'
export const CLEAR_FORMULARIO_VISITA_SUCCESS = 'CLEAR_FORMULARIO_VISITA_SUCCESS'
export const CLEAR_FORMULARIO_VISITA_ERROR = 'CLEAR_FORMULARIO_VISITA_ERROR'

export const REPLACE_FORMULARIO_VISITA_ATTRIBUTES = 'REPLACE_FORMULARIO_VISITA_ATTRIBUTES'

// ----------- Filtros Visita -----------
export const GET_FILTRO_INICIAL_VISITA_REQUEST = 'GET_FILTRO_INICIAL_VISITA_REQUEST'
export const GET_FILTRO_INICIAL_VISITA_SUCCESS = 'GET_FILTRO_INICIAL_VISITA_SUCCESS'
export const GET_FILTRO_INICIAL_VISITA_ERROR = 'GET_FILTRO_INICIAL_VISITA_ERROR'

export const GET_FILTRO_PRIORIZADA_VISITA_REQUEST = 'GET_FILTRO_PRIORIZADA_VISITA_REQUEST'
export const GET_FILTRO_PRIORIZADA_VISITA_SUCCESS = 'GET_FILTRO_PRIORIZADA_VISITA_SUCCESS'
export const GET_FILTRO_PRIORIZADA_VISITA_ERROR = 'GET_FILTRO_PRIORIZADA_VISITA_ERROR'

export const CLEAR_FILTRO_VISITA_SUCCESS = 'CLEAR_FILTRO_VISITA_SUCCESS'
export const RESTORE_BACKUP_FILTRO_VISITA_SUCCESS = 'RESTORE_BACKUP_FILTRO_VISITA_SUCCESS'

export const REPLACE_FILTRO_VISITA_ATTRIBUTES = 'REPLACE_FILTRO_VISITA_ATTRIBUTES'

export const SET_VISITA_FILTER_PARAMS = 'SET_VISITA_FILTER_PARAMS'

// ----------- Formulario Riesgo -----------
export const GET_FORMULARIO_INICIAL_RIESGO_REQUEST = 'GET_FORMULARIO_INICIAL_RIESGO_REQUEST'
export const GET_FORMULARIO_INICIAL_RIESGO_SUCCESS = 'GET_FORMULARIO_INICIAL_RIESGO_SUCCESS'
export const GET_FORMULARIO_INICIAL_RIESGO_ERROR = 'GET_FORMULARIO_INICIAL_RIESGO_ERROR'

export const GET_PREGUNTAS_FORMULARIO_RIESGO_REQUEST = 'GET_PREGUNTAS_FORMULARIO_RIESGO_REQUEST'
export const GET_PREGUNTAS_FORMULARIO_RIESGO_SUCCESS = 'GET_PREGUNTAS_FORMULARIO_RIESGO_SUCCESS'
export const GET_PREGUNTAS_FORMULARIO_RIESGO_ERROR = 'GET_PREGUNTAS_FORMULARIO_RIESGO_ERROR'

export const CLEAR_FORMULARIO_RIESGO_REQUEST = 'CLEAR_FORMULARIO_RIESGO_REQUEST'
export const CLEAR_FORMULARIO_RIESGO_SUCCESS = 'CLEAR_FORMULARIO_RIESGO_SUCCESS'
export const CLEAR_FORMULARIO_RIESGO_ERROR = 'CLEAR_FORMULARIO_RIESGO_ERROR'

export const REPLACE_FORMULARIO_RIESGO_ATTRIBUTES = 'REPLACE_FORMULARIO_RIESGO_ATTRIBUTES'

// ----------- Connection -----------
export const NETWORK_OPERATION_START = 'NETWORK_OPERATION_START'
export const NETWORK_OPERATION_END = 'NETWORK_OPERATION_END'

// --- CLEAR --- //
export const CLEAR_DATA = 'CLEAR_DATA'

//-- Enrolador Dispositivo Colaborador ---//
export const GET_ENROLADOR_DEVICE_REQUEST = 'GET_ENROLADOR_DEVICE_REQUEST'
export const GET_ENROLADOR_DEVICE_SUCCESS = 'GET_ENROLADOR_DEVICE_SUCCESS'
export const GET_ENROLADOR_DEVICE_ERROR = 'GET_ENROLADOR_DEVICE_ERROR'

//-- Mensajes Notificaciones ---//
export const GET_MENSAJES_NOTIFICACIONES_REQUEST = 'GET_MENSAJES_NOTIFICACIONES_REQUEST'
export const GET_MENSAJES_NOTIFICACIONES_SUCCESS = 'GET_MENSAJES_NOTIFICACIONES_SUCCESS'
export const GET_MENSAJES_NOTIFICACIONES_ERROR = 'GET_MENSAJES_NOTIFICACIONES_ERROR'

export const GET_CANT_MENSAJES_NO_LEIDOS_REQUEST = 'GET_CANT_MENSAJES_NO_LEIDOS_REQUEST'
export const GET_CANT_MENSAJES_NO_LEIDOS_SUCCESS = 'GET_CANT_MENSAJES_NO_LEIDOS_SUCCESS'
export const GET_CANT_MENSAJES_NO_LEIDOS_ERROR   = 'GET_CANT_MENSAJES_NO_LEIDOS_ERROR'

export const MARCAR_MENSAJES_LEIDOS_REQUEST = 'MARCAR_MENSAJES_LEIDOS_REQUEST '
export const MARCAR_MENSAJES_LEIDOS_SUCCESS = 'MARCAR_MENSAJES_LEIDOS_SUCCESS'
export const MARCAR_MENSAJES_LEIDOS_ERROR   = 'MARCAR_MENSAJES_LEIDOS_ERROR'

export const CLEAR_MENSAJES_NOTIFICACIONES = 'CLEAR_MENSAJES_NOTIFICACIONES'

//-- Obtener Plataforma ---//

export const GET_OBTENER_PLATAFORMA_REQUEST = 'GET_OBTENER_PLATAFORMA_REQUEST'
export const GET_OBTENER_PLATAFORMA_SUCCESS = 'GET_OBTENER_PLATAFORMA_SUCCESS'
export const GET_OBTENER_PLATAFORMA_ERROR   = 'GET_OBTENER_PLATAFORMA_ERROR'


//-- obtenerPeriodos --- //

export const GET_OBTENER_PERIODOS_REQUEST = 'GET_OBTENER_PERIODOS_REQUEST'
export const GET_OBTENER_PERIODOS_SUCCESS = 'GET_OBTENER_PERIODOS_SUCCESS'
export const GET_OBTENER_PERIODOS_ERROR   = 'GET_OBTENER_PERIODOS_ERROR'